### ISSUE TITLE
rlsa - listtodos regex change

### ISSUE THREAD

**Issue by the1ts** [smajda/todo.actions.d#1]
Hey,
Like the rlsa action for todo.txt, I've made a bit of a change for my local copy, I keep my config files with my todo files so have tightened the grep regex. Also changed the find (-depth 1 errors with gnu version of find)

--- rlsa        2009-05-15 15:22:46.000000000 +0100
+++ /net/gateway/home/paulbm/.todo.actions.d/rlsa       2009-05-15 15:08:57.000000000 +0100
@@ -16,7 +16,7 @@
 ## OR
 ## 2. or figure them out manually
 cd "$TODO_DIR"
-listtodos=`find . -depth 1 -type f | sed 's/\.\///g' | grep -Ev "^\.|\.bak$|\.tmp$|^report|^done"`
+listtodos=`find . -maxdepth 1 -type f | sed 's/\.\///g' | grep -Ev "^\.|\.cfg$|\.bak$|\.tmp$|^report|^done"`
 # ^^ add exceptions up there
 mytodos=($listtodos);

**Comment by smajda** [comment]
Thanks! I just made both of these changes to my copy as well.
